=== Blacktron/netTransformer/iTopologyManager/parameterFactory/src/main/resources/parameterFactory/conf/xsd/param-factory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ param-factory.xsd
  ~
  ~ This work is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published
  ~ by the Free Software Foundation; either version 2 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This work is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  ~ USA
  ~
  ~ Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
  -->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="param-factories" type="param-factoriesType"/>
  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="class" use="required"/>
  </xs:complexType>
  <xs:complexType name="param-factory-element-typesType">
    <xs:sequence>
      <xs:element type="typeType" name="type" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="param-factoriesType">
    <xs:sequence>
      <xs:element type="param-factory-element-typesType" name="param-factory-element-types"/>
      <xs:element type="param-factoryType" name="param-factory" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="param-factoryType">
    <xs:sequence>
      <xs:element type="param-factory-elementType" name="param-factory-element" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="param-factory-elementType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="required"/>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Blacktron/netTransformer/iTopologyManager/parameterFactory/conf/xml/serv-param-factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ iTransformer is an open source tool able to discover and transform
  ~  IP network infrastructures.
  ~  Copyright (C) 2012  http://itransformers.net
  ~
  ~  This program is free software: you can redistribute it and/or modify
  ~  it under the terms of the GNU General Public License as published by
  ~  the Free Software Foundation, either version 3 of the License, or
  ~  any later version.
  ~
  ~  This program is distributed in the hope that it will be useful,
  ~  but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~  GNU General Public License for more details.
  ~
  ~  You should have received a copy of the GNU General Public License
  ~  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<param-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/param-factory.xsd">
    <param-factory-element-types>
        <type name="manual" class="com.parameterfactory.impl.GUIParamFactoryElement"/>
        <type name="graphml" class="com.parameterfactory.impl.MapDerivedParamFactoryElement">
            <param name="contextKey">graphml</param>
        </type>
        <type name="resource" class="com.parameterfactory.impl.MapDerivedParamFactoryElement">
            <param name="contextKey">connection-params</param>
        </type>
        <type name="deviceData" class="com.parameterfactory.impl.XmlParamFactoryElement">
            <param name="contextXmlFileNameKey">xmlFileName</param>
        </type>
    </param-factory-element-types>
    <param-factory name="add">
        <param-factory-element type="manual">
            <param name="Service Name"/>
            <param name="Service Type"/>
            <param name="Service Locations"/>
        </param-factory-element>
        <param-factory-element type="resource">
            <param name="username"/>
            <param name="password"/>
        </param-factory-element>
    </param-factory>
     <param-factory name="delete">
        <param-factory-element type="manual">
            <param name="Service Name"/>
            <param name="Service Type"/>
            <param name="Service Locations"/>
        </param-factory-element>
        <param-factory-element type="resource">
            <param name="username"/>
            <param name="password"/>
        </param-factory-element>
    </param-factory>
    <param-factory name="modify">
        <param-factory-element type="manual">
            <param name="Service Name"/>
            <param name="Service Type"/>
            <param name="Service Locations"/>
        </param-factory-element>
        <param-factory-element type="resource">
            <param name="username"/>
            <param name="password"/>
        </param-factory-element>
    </param-factory>
</param-factories>
