=== Blacktron/netTransformer/parameterFactory/parameterFactoryAPI/src/main/resources/conf/xsd/param-factory-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="param-factories-config" type="param-factories-configType"/>
  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="class" use="optional"/>
  </xs:complexType>
  <xs:complexType name="param-factory-element-typesType">
    <xs:sequence>
      <xs:element type="typeType" name="type" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="param-factories-configType">
    <xs:sequence>
      <xs:element type="param-factory-element-typesType" name="param-factory-element-types"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Blacktron/netTransformer/parameterFactory/xmlParameterFactory/src/test/java/resources/xmlParameterFactoryTests/param-factory-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<param-factories-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../../xsd/param-factory-config.xsd">
    <param-factory-element-types>
        <type name="manual" class="net.itransformers.parameterfactoryapi.impl.GUIParamFactoryElement"/>
        <type name="graphml" class="net.itransformers.parameterfactoryapi.impl.MapDerivedParamFactoryElement">
            <param name="contextKey">graphml</param>
        </type>
        <type name="resource" class="net.itransformers.parameterfactoryapi.impl.MapDerivedParamFactoryElement">
            <param name="contextKey">connection-params</param>
        </type>
        <type name="deviceData" class="net.itransformers.parameterfactoryapi.impl.XmlParamFactoryElement">
            <param name="contextXmlFileNameKey">xmlFileName</param>
        </type>
    </param-factory-element-types>
</param-factories-config>
