=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/xsd/fulfilment-factory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fulfilment-factories" type="fulfilment-factoriesType"/>
  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="class" use="optional"/>
  </xs:complexType>
  <xs:complexType name="fulfilment-factory-typesType">
    <xs:sequence>
      <xs:element type="typeType" name="type" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fulfilment-factoriesType">
    <xs:sequence>
      <xs:element type="fulfilment-factory-typesType" name="fulfilment-factory-types"/>
      <xs:element type="fulfilment-factoryType" name="fulfilment-factory" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fulfilment-factoryType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="resourceName" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="parameterFactoryName" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/xml/fulfilment-factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <type name="ConfigureInterface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ConfigureInterface</param>
            <param name="commands">fulfilment-factory/conf/txt/test.txt</param>
        </type>
        <type name="CreateVRF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfilment-factory/conf/txt/create_vrf</param>
        </type>
         <type name="ApplyVRF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfilment-factory/conf/txt/apply_vrf.txt</param>
        </type>
        <type name="AddDefaultToVRF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfilment-factory/conf/txt/add_default_to_vrf.txt</param>
        </type>
        <type name="xsl" class="com.fulfilmentfactory.impl.XslFulfilmentImpl">
            <param name="xslFileName">fulfilment-factory/conf/xslt/setDeviceLocation.xslt</param>
        </type>
        <type name="xsl2" class="com.cdsd.Xsl">
            <param name="xslFileName">some2.xsl</param>
        </type>
    </fulfilment-factory-types>
    <fulfilment-factory name="create_vrf" resourceName="cisco" type="CreateVRF" parameterFactoryName="CreateVRF"/>
    <fulfilment-factory name="apply_vrf" resourceName="cisco" type="ApplyVRF" parameterFactoryName="ApplyVRF"/>
    <fulfilment-factory name="add_default_to_vrf" resourceName="cisco" type="AddDefaultToVRF" parameterFactoryName="addDefaultToVRF"/>
    <fulfilment-factory name="ConfigureInterface" resourceName="cisco" type="ConfigureInterface" parameterFactoryName="ConfigureInterface"/>
    <fulfilment-factory name="test" resourceName="cisco" type="CreateVRF" parameterFactoryName="CreateVRF"/>
    <fulfilment-factory name="testXSL" resourceName="cisco" type="xsl" parameterFactoryName="testXSL"/>

</fulfilment-factories>
