=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/xsd/fulfilment-factory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fulfilment-factories" type="fulfilment-factoriesType"/>
  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="class" use="optional"/>
  </xs:complexType>
  <xs:complexType name="fulfilment-factory-typesType">
    <xs:sequence>
      <xs:element type="typeType" name="type" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fulfilment-factoriesType">
    <xs:sequence>
      <xs:element type="fulfilment-factory-typesType" name="fulfilment-factory-types"/>
      <xs:element type="fulfilment-factoryType" name="fulfilment-factory" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fulfilment-factoryType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="resourceName" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="parameterFactoryName" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/fulfillmentFactory/xml/fulfilment-IPv4to6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ fulfilment-IPv4to6.xml
  ~
  ~ This work is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published
  ~ by the Free Software Foundation; either version 2 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This work is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  ~ USA
  ~
  ~ Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
  -->

<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <!--cisco fulfillment-->
        <type name="c_ipv6Forwarding" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Forwarding</param>
            <param name="commands">fulfillmentFactory/conf/txt/cisco/ipv6Forwarding.templ</param>
        </type>
        <type name="c_ipv6Interface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Interface</param>
            <param name="commands">fulfillmentFactory/conf/txt/cisco/ipv6Interface.templ</param>
        </type>
        <type name="c_IPv6Verify" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6Verify</param>
            <param name="commands">fulfillmentFactory/conf/txt/cisco/IPv6Verify.templ</param>
        </type>
        <type name="c_IPv6OSPF" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF</param>
            <param name="commands">fulfillmentFactory/conf/txt/cisco/IPv6OSPF.templ</param>
        </type>
       <!--Huawei Fulfillment-->
        <type name="h_IPv6OSPF_interface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF_interface</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/IPv6OSPF_interface.templ</param>
        </type>
        <type name="h_ipv6Forwarding" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/ipv6Forwarding.templ</param>
        </type>
        <type name="h_ipv6Interface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/ipv6Interface.templ</param>
        </type>
        <type name="h_IPv6Verify" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/IPv6Verify.templ</param>
        </type>
        <type name="h_IPv6OSPF" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/IPv6OSPF.templ</param>
        </type>
        <type name="h_IPv6OSPF_interface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF_interface</param>
            <param name="commands">fulfillmentFactory/conf/txt/huawei/IPv6OSPF_interface.templ</param>
        </type>
        <!--Juniper Fulfillment-->

        <!--type name="j_ipv6Forwarding" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfillmentFactory/conf/txt/juniper/ipv6Forwarding.templ</param>
        </type-->
        <type name="j_ipv6Interface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfillmentFactory/conf/txt/juniper/ipv6Interface.templ</param>
        </type>
        <type name="j_IPv6Verify" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfillmentFactory/conf/txt/juniper/IPv6Verify.templ</param>
        </type>
        <type name="j_IPv6OSPF_14" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfillmentFactory/conf/txt/juniper/IPv6OSPF_14.templ</param>
        </type>
        <type name="j_IPv6OSPF_16_" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfillmentFactory/conf/txt/juniper/IPv6OSPF_16.templ</param>
        </type>

        <type name="xsl" class="com.cdsd.Xsl">
            <param name="xslFileName">some.xsl</param>
            <param name="xslFileName">some.xsl</param>
        </type>
        <type name="xsl2" class="com.cdsd.Xsl">
            <param name="xslFileName">some2.xsl</param>
        </type>
    </fulfilment-factory-types>
    <fulfilment-factory name="cIPv6Forwarding" resourceName="cisco" type="c_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="cIPv6Interface" resourceName="cisco" type="c_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="cIPv6OSPF" resourceName="cisco" type="c_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="cIPv6OSPF_interface" resourceName="cisco" type="c_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="cIPv6Verify" resourceName="cisco" type="c_IPv6Verify" parameterFactoryName="IPv6Verify"/>

    <fulfilment-factory name="hIPv6Forwarding" resourceName="huawei" type="h_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="hIPv6Interface" resourceName="huawei" type="h_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="hIPv6OSPF" resourceName="huawei" type="h_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="hIPv6OSPF_interface" resourceName="huawei" type="h_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="hIPv6Verify" resourceName="huawei" type="h_IPv6Verify" parameterFactoryName="IPv6Verify"/>

    <fulfilment-factory name="jIPv6Interface" resourceName="juniper" type="j_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="jIPv6OSPF_14" resourceName="juniper" type="j_IPv6OSPF_14" parameterFactoryName="basic"/>
    <fulfilment-factory name="jIPv6OSPF_16" resourceName="juniper" type="j_IPv6OSPF_16" parameterFactoryName="basic"/>
    <fulfilment-factory name="jIPv6Verify" resourceName="juniper" type="j_IPv6Verify" parameterFactoryName="IPv6Verify"/>

</fulfilment-factories>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/fulfillmentFactory/xml/fulfilment-factory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ fulfilmentFactory.xml
  ~
  ~ This work is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published
  ~ by the Free Software Foundation; either version 2 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This work is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  ~ USA
  ~
  ~ Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
  -->

<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <type name="ConfigureInterface" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ConfigureInterface</param>
            <param name="commands">fulfillmentFactory/conf/txt/test.templ</param>
        </type>
        <type name="CreateVRF" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfillmentFactory/conf/txt/create_vrf.templ</param>
        </type>
         <type name="ApplyVRF" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfillmentFactory/conf/txt/apply_vrf.templ</param>
        </type>
        <type name="AddDefaultToVRF" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">VPN_activator</param>
            <param name="commands">fulfillmentFactory/conf/txt/add_default_to_vrf.templ</param>
        </type>
        <type name="xsl" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.XslFulfilmentImpl">
            <param name="xslFileName">fulfillmentFactory/conf/xslt/setDeviceLocation.templ</param>
        </type>
        <type name="xsl2" class="com.cdsd.Xsl">
            <param name="xslFileName">some2.xsl</param>
        </type>
    </fulfilment-factory-types>
    <fulfilment-factory name="create_vrf" resourceName="cisco" type="CreateVRF" parameterFactoryName="CreateVRF"/>
    <fulfilment-factory name="apply_vrf" resourceName="cisco" type="ApplyVRF" parameterFactoryName="ApplyVRF"/>
    <fulfilment-factory name="add_default_to_vrf" resourceName="cisco" type="AddDefaultToVRF" parameterFactoryName="addDefaultToVRF"/>
    <fulfilment-factory name="ConfigureInterface" resourceName="cisco" type="ConfigureInterface" parameterFactoryName="ConfigureInterface"/>
    <fulfilment-factory name="test" resourceName="cisco" type="CreateVRF" parameterFactoryName="CreateVRF"/>
    <fulfilment-factory name="testXSL" resourceName="cisco" type="xsl" parameterFactoryName="testXSL"/>

</fulfilment-factories>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/fulfillmentFactory/xml/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ services.xml
  ~
  ~ This work is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published
  ~ by the Free Software Foundation; either version 2 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This work is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  ~ USA
  ~
  ~ Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
  -->

<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <type name="add" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ADD</param>
            <param name="commands">fulfilment-factory/conf/txt/services/add.txt</param>
        </type>
        <type name="delete" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">DELETE</param>
            <param name="commands">fulfilment-factory/conf/txt/services/delete.txt</param>
        </type>
        <type name="modify" class="net.itransformers.topologyviewer.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">MODIFY</param>
            <param name="commands">fulfilment-factory/conf/txt/services/modify.txt</param>
        </type>
    </fulfilment-factory-types>
    <fulfilment-factory name="add" resourceName="SERVER" type="add" parameterFactoryName="add"/>
    <fulfilment-factory name="delete" resourceName="SERVER" type="delete" parameterFactoryName="delete"/>
    <fulfilment-factory name="modify" resourceName="SERVER" type="modify" parameterFactoryName="modify"/>
</fulfilment-factories>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/xml/fulfilment-4to6trans.xml
<?xml version="1.0" encoding="UTF-8"?>
<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <!--cisco fulfillment-->
        <type name="c_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/ipv6Forwarding.txt</param>
        </type>
        <type name="c_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/ipv6Interface.txt</param>
        </type>
        <type name="c_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/IPv6Verify.txt</param>
        </type>
        <type name="c_IPv6OSPF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/IPv6OSPF.txt</param>
        </type>
       <!--Huawei Fulfillment-->
        <type name="h_IPv6OSPF_interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF_interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/IPv6OSPF_interface.txt</param>
        </type>
        <type name="h_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/ipv6Forwarding.txt</param>
        </type>
        <type name="h_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/ipv6Interface.txt</param>
        </type>
        <type name="h_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/IPv6Verify.txt</param>
        </type>
        <type name="h_IPv6OSPF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/IPv6OSPF.txt</param>
        </type>
        <type name="h_IPv6OSPF_interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF_interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/IPv6OSPF_interface.txt</param>
        </type>
        <!--Juniper Fulfillment-->

        <!--type name="j_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/ipv6Forwarding.txt</param>
        </type-->
        <type name="j_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/ipv6Interface.txt</param>
        </type>
        <type name="j_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/IPv6Verify.txt</param>
        </type>
        <type name="j_IPv6OSPF_14" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/IPv6OSPF_14.txt</param>
        </type>
        <type name="j_IPv6OSPF_16_" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/IPv6OSPF_16.txt</param>
        </type>

        <type name="xsl" class="com.cdsd.Xsl">
            <param name="xslFileName">some.xsl</param>
            <param name="xslFileName">some.xsl</param>
        </type>
        <type name="xsl2" class="com.cdsd.Xsl">
            <param name="xslFileName">some2.xsl</param>
        </type>
    </fulfilment-factory-types>
    <fulfilment-factory name="cIPv6Forwarding" resourceName="cisco" type="c_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="cIPv6Interface" resourceName="cisco" type="c_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="cIPv6OSPF" resourceName="cisco" type="c_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="cIPv6OSPF_interface" resourceName="cisco" type="c_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="cIPv6Verify" resourceName="cisco" type="c_IPv6Verify" parameterFactoryName="IPv6Verify"/>

    <fulfilment-factory name="hIPv6Forwarding" resourceName="huawei" type="h_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="hIPv6Interface" resourceName="huawei" type="h_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="hIPv6OSPF" resourceName="huawei" type="h_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="hIPv6OSPF_interface" resourceName="huawei" type="h_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="hIPv6Verify" resourceName="huawei" type="h_IPv6Verify" parameterFactoryName="IPv6Verify"/>

    <fulfilment-factory name="jIPv6Interface" resourceName="juniper" type="j_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="jIPv6OSPF_14" resourceName="juniper" type="j_IPv6OSPF_14" parameterFactoryName="basic"/>
    <fulfilment-factory name="jIPv6OSPF_16" resourceName="juniper" type="j_IPv6OSPF_16" parameterFactoryName="basic"/>
    <fulfilment-factory name="jIPv6Verify" resourceName="juniper" type="j_IPv6Verify" parameterFactoryName="IPv6Verify"/>

</fulfilment-factories>

=== Blacktron/netTransformer/iTopologyManager/fulfilmentFactory/src/main/resources/fulfillmentFactory/xml/fulfilment-IPv4to6_undo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ fulfilment-IPv4to6_undo.xml
  ~
  ~ This work is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published
  ~ by the Free Software Foundation; either version 2 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This work is distributed in the hope that it will be useful, but
  ~ WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
  ~ USA
  ~
  ~ Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
  -->

<fulfilment-factories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/fulfilment-factory.xsd">
    <fulfilment-factory-types>
        <!--Cisco fulfillment types-->
        <type name="undo_c_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/undo/ipv6Forwarding.txt</param>
        </type>
        <type name="undo_c_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/undo/ipv6Interface.txt</param>
        </type>
        <type name="undo_c_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/undo/IPv6Verify.txt</param>
        </type>
        <type name="undo_c_IPv6OSPF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/cisco/undo/IPv6OSPF.txt</param>
        </type>
        <!--Huawei fulfillment types-->
        <type name="undo_h_IPv6OSPF_interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF_interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/undo/IPv6OSPF_interface.txt</param>
        </type>
        <type name="undo_h_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/undo/ipv6Forwarding.txt</param>
        </type>
        <type name="undo_h_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/undo/ipv6Interface.txt</param>
        </type>
        <type name="undo_h_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/undo/IPv6Verify.txt</param>
        </type>
        <type name="undo_h_IPv6OSPF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/huawei/undo/IPv6OSPF.txt</param>
        </type>
        <!--Juniper fulfillment-types-->
        <type name="undo_j_IPv6OSPF_interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">IPv6OSPF_interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/undo/IPv6OSPF_interface.txt</param>
        </type>
        <type name="undo_j_ipv6Forwarding" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Forwarding</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/undo/ipv6Forwarding.txt</param>
        </type>
        <type name="undo_j_ipv6Interface" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_ipv6Interface</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/undo/ipv6Interface.txt</param>
        </type>
        <type name="undo_j_IPv6Verify" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6Verify</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/undo/IPv6Verify.txt</param>
        </type>
        <type name="undo_j_IPv6OSPF" class="com.fulfilmentfactory.impl.TestFulfilmentImpl">
            <param name="cmd">huawei_IPv6OSPF</param>
            <param name="commands">fulfilment-factory/conf/txt/4to6trans/juniper/undo/IPv6OSPF.txt</param>
        </type>
        <!--xsl fulfillment-->
        <type name="xsl" class="com.cdsd.Xsl">
            <param name="xslFileName">some.xsl</param>
            <param name="xslFileName">some.xsl</param>
        </type>
        <type name="xsl2" class="com.cdsd.Xsl">
            <param name="xslFileName">some2.xsl</param>
        </type>
    </fulfilment-factory-types>

    <fulfilment-factory name="undo_cIPv6Forwarding" resourceName="cisco" type="undo_c_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="undo_cIPv6Interface" resourceName="cisco" type="undo_c_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="undo_cIPv6OSPF" resourceName="cisco" type="undo_c_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="undo_cIPv6OSPF_interface" resourceName="cisco" type="undo_c_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="undo_cIPv6Verify" resourceName="cisco" type="undo_c_IPv6Verify" parameterFactoryName="IPv6Verify"/>


    <fulfilment-factory name="undo_hIPv6Forwarding" resourceName="huawei" type="undo_h_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="undo_hIPv6Interface" resourceName="huawei" type="undo_h_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="undo_hIPv6OSPF" resourceName="huawei" type="undo_h_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="undo_hIPv6OSPF_interface" resourceName="huawei" type="undo_h_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="undo_hIPv6Verify" resourceName="huawei" type="undo_h_IPv6Verify" parameterFactoryName="IPv6Verify"/>


    <fulfilment-factory name="undo_jIPv6Forwarding" resourceName="juniper" type="undo_j_ipv6Forwarding" parameterFactoryName="ipv6Forwarding"/>
    <fulfilment-factory name="undo_jIPv6Interface" resourceName="juniper" type="undo_j_ipv6Interface" parameterFactoryName="ipv6Interface"/>
    <fulfilment-factory name="undo_jIPv6OSPF" resourceName="juniper" type="undo_j_IPv6OSPF" parameterFactoryName="IPv6OSPF"/>
    <fulfilment-factory name="undo_jIPv6OSPF_interface" resourceName="juniper" type="undo_j_IPv6OSPF_interface" parameterFactoryName="IPv6OSPF_interface"/>
    <fulfilment-factory name="undo_jIPv6Verify" resourceName="juniper" type="undo_j_IPv6Verify" parameterFactoryName="IPv6Verify"/>
</fulfilment-factories>
